name: CI/CD Pipeline with Rollback and Monitoring

on:
  push:
    branches:
      - master
      - Staging
  pull_request:
    branches:
      - master
      - Staging

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Build project
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist

      - name: Verify build output
        run: ls -la dist

  deploy-staging:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: dist

      - name: List current directory
        run: ls -la

      - name: List full directory tree
        run: pwd      

      - name: Deploy to Staging (Netlify)
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: npx netlify-cli deploy --dir=/home/runner/work/Group_BSE24-17FE/Group_BSE24-17FE --prod --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN

      - name: Check Deployment Status
        run: |
          if [ $(npx netlify-cli status --site $NETLIFY_SITE_ID | grep 'state: live' | wc -l) -eq 0 ]; then
            echo "Deployment failed. Initiating rollback..."
            npx netlify-cli deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --rollback
          else
            echo "Deployment successful."
          fi

  deploy-production:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: dist

      - name: Deploy to Production (Netlify)
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_PRODUCTION_SITE_ID }}
        run: npx netlify-cli deploy --dir=/home/runner/work/Group_BSE24-17FE/Group_BSE24-17FE --prod --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN

      - name: Check Deployment Status
        run: |
          if [ $(npx netlify-cli status --site $NETLIFY_PRODUCTION_SITE_ID | grep 'state: live' | wc -l) -eq 0 ]; then
            echo "Deployment failed. Initiating rollback..."
            npx netlify-cli deploy --site $NETLIFY_PRODUCTION_SITE_ID --auth $NETLIFY_AUTH_TOKEN --rollback
          else
            echo "Deployment successful."
          fi
