name: CI/CD Pipeline with Rollback and Monitoring

on:
  push:
    branches:
      - master
      - Staging
  pull_request:
    branches:
      - master
      - Staging

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Build project
        run: npm run build

  deploy-staging:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/Staging'
    steps:
      - name: Deploy to Staging (Netlify)
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: npx netlify-cli deploy --dir=dist --prod --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN

  # deploy-production:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   if: github.ref == 'refs/heads/master'
  #   steps:
  #     - name: Deploy to Production (Netlify)
  #       env:
  #         NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
  #         NETLIFY_SITE_ID: ${{ secrets.NETLIFY_PRODUCTION_SITE_ID }}
  #       run: npx netlify-cli deploy --dir=dist --prod --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN

  #     - name: Log Deployment Success
  #       run: echo "Deployment to production was successful"

  #     - name: Get Previous Deployment ID
  #       id: previous-deploy
  #       run: |
  #         PREVIOUS_DEPLOY=$(npx netlify api listSiteDeploys --data '{"site_id": "'$NETLIFY_SITE_ID'"}' | jq -r '.[1].id')
  #         echo "Previous deployment ID: $PREVIOUS_DEPLOY"
  #         echo "::set-output name=previous_deploy::$PREVIOUS_DEPLOY"

  #     - name: Rollback on Failure
  #       if: failure()
  #       env:
  #         NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
  #         NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
  #         PREVIOUS_DEPLOY: ${{ steps.previous-deploy.outputs.previous_deploy }}
  #       run: |
  #         if [ -z "$PREVIOUS_DEPLOY" ]; then
  #           echo "No previous deployment found, skipping rollback."
  #         else
  #           echo "Rolling back to deployment ID $PREVIOUS_DEPLOY"
  #           npx netlify deploy --prod --site $NETLIFY_SITE_ID --alias "$PREVIOUS_DEPLOY"
  #         fi

  
